[package]
name = "divisioner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob = "0.3.1"
clap = { version = "4.2.1", features = ["derive"] }
zip = "0.6.4"
indicatif = "0.17.3"
csv = "1.2.1"
